name: CI/CD

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/Checkout@v2

    - name: set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        npm install

    - name: Build Docker image
      run: |
        docker build -t devops .
#private key added
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/your/app
          git pull origin main
          docker build -t devops .
          docker stop devops || true
          docker rm devops || true
          docker run -d -p 10049:10049 --name devops devops 

